### PR TITLE
Bump events to v3

### PR DESCRIPTION
**Pull request by archmoj**
See https://github.com/glslify/glslify/pull/142 and https://github.com/plotly/plotly.js/pull/5297.

Addressing https://github.com/plotly/plotly.js/issues/5289#issuecomment-730518332

@rreusser 
cc: @alexcjohnson

### CODE REVIEW

**Comment by rreusser** [comment]
As this is a compile-time dependency of glslify, nothing jumps out as problematic. You can find the [events release notes here](https://github.com/browserify/events/blob/master/History.md). Lack of IE8 support for bundling should be… acceptable, I think. As long as tests pass, seems fine to me. 👍

**Comment by archmoj** [comment]
> As this is a compile-time dependency of glslify, nothing jumps out as problematic. You can find the [events release notes here](https://github.com/browserify/events/blob/master/History.md). Lack of IE8 support for bundling should be… acceptable, I think. As long as tests pass, seems fine to me. 👍

Are you going to release a major or patch please?

**Comment by rreusser** [comment]
As this doesn't affect usage of glslify-deps, I think this seems like it ought to be a patch version. `1.3.2`, I think. Releasing…

**Review by rreusser — APPROVED** [review]
Ran the tests, and appears good to me. Since this doesn't affect usage of glslify-deps, I believe, will follow with a patch increment.

**Pull request merged**
